# Physiologic plausibility bounds
by_loinc:
  "2339-0":
    units: ["mg/dL"]
    min: 10
    max: 2500

  "4548-4":
    units: ["%"]
    min: 0
    max: 25

  "2093-3":
    units: ["mg/dL"]
    min: 30
    max: 2000

  "13457-7":
    units: ["mg/dL"]
    min: 0
    max: 1000

  "2085-9":
    units: ["mg/dL"]
    min: 0
    max: 200

  "2571-8":
    units: ["mg/dL"]
    min: 0
    max: 10000

  "1920-8":
    units: ["U/L"]
    min: 0
    max: 20000

  "1742-6":
    units: ["U/L"]
    min: 0
    max: 10000

  "1988-5":
    units: ["mg/L"]
    min: 0
    max: 500

  "6690-2":
    units: ["10^3/uL", "x10^3/uL", "10*3/uL"]
    min: 0
    max: 500

  "8480-6":
    units: ["mmHg"]
    min: 50
    max: 300

  "8867-4":
    units: ["/min", "beats/min", "bpm"]
    min: 0
    max: 300

  "59408-5":
    units: ["%"]
    min: 30
    max: 100

  "39156-5":
    units: ["kg/m2", "kg/m^2"]
    min: 5
    max: 100
